# Generated by Django 2.1.10 on 2019-08-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact_num', models.IntegerField()),
                ('status', models.CharField(choices=[('coming', 'Coming'), ('on going', 'On Going'), ('not coming', 'Not Coming'), ('reliver', 'Reliver'), ('on call', 'On Call'), ('not sure', 'Not Sure'), ('leave', 'Leave'), ('Out', 'Out')], max_length=60, null=True)),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='branches.Clinic')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='branches.Specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wenesday', 'Wenesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=60, null=True)),
                ('schedule_time_in', models.CharField(choices=[('12:00AM', '12:00AM'), ('01:00AM', '01:00AM'), ('02:00AM', '02:00AM'), ('03:00AM', '03:00AM'), ('04:00AM', '04:00AM'), ('05:00AM', '05:00AM'), ('06:00AM', '06:00AM'), ('07:00AM', '07:00AM'), ('08:00AM', '08:00AM'), ('09:00AM', '09:00AM'), ('10:00AM', '10:00AM'), ('11:00AM', '11:00AM')], max_length=60, null=True)),
                ('schedule_time_out', models.CharField(choices=[('12:00PM', '12:00PM'), ('01:00PM', '01:00PM'), ('02:00PM', '02:00PM'), ('03:00PM', '03:00PM'), ('04:00PM', '04:00PM'), ('05:00PM', '05:00PM'), ('06:00PM', '06:00PM'), ('07:00PM', '07:00PM'), ('08:00PM', '08:00PM'), ('09:00PM', '09:00PM'), ('10:00PM', '10:00PM'), ('11:00PM', '11:00PM')], max_length=60, null=True)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physicians', to='doctors.Physician')),
            ],
        ),
    ]
