# Generated by Django 2.1.10 on 2019-08-13 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact_num', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('coming', 'Coming'), ('on going', 'On Going'), ('not coming', 'Not Coming'), ('reliver', 'Reliver'), ('on call', 'On Call'), ('not sure', 'Not Sure'), ('leave', 'Leave'), ('Out', 'Out')], max_length=60, null=True)),
                ('schedule_day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wenesday', 'Wenesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=60, null=True)),
                ('schedule_time', models.DateTimeField()),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='branches.Clinic')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='branches.Specialization')),
            ],
        ),
    ]
